name: kaching
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_ui_auth: ^1.16.1
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^1.4.1
  cloud_firestore: ^5.5.0
  firebase_database: ^11.0.4
  image_picker: ^1.0.4
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  provider: ^6.1.1
  http: ^1.1.0
  # Charts
  fl_chart: ^0.65.0
  firebase_storage: 12.4.5
  path: ^1.8.3
  cross_file: ^0.3.3+4
  # Add these dependencies for PDF generation and sharing
  pdf: ^3.10.4
  path_provider: ^2.1.1
  open_file: ^3.3.2
  share_plus: ^7.1.0
  # OCR for receipt scanning
  google_mlkit_text_recognition: ^0.13.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/kaching.png
