// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMFWDeIa-IdxzRsT1AfNXF3fGLCoCoGHA',
    appId: '1:175995407076:web:d4efd0d8553f2f68cf7af1',
    messagingSenderId: '175995407076',
    projectId: 'ka-ching-a9b4f',
    authDomain: 'ka-ching-a9b4f.firebaseapp.com',
    storageBucket: 'ka-ching-a9b4f.firebasestorage.app',
    measurementId: 'G-FVNKR35ZGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvMmI_VhJuCPUW07Fz3xLWeN7haP1nn0',
    appId: '1:175995407076:android:d56c19bff56634cfcf7af1',
    messagingSenderId: '175995407076',
    projectId: 'ka-ching-a9b4f',
    storageBucket: 'ka-ching-a9b4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOF9EWnUhY47NcptbWPhFSSrzl5S3pf_o',
    appId: '1:175995407076:ios:2af181831945c986cf7af1',
    messagingSenderId: '175995407076',
    projectId: 'ka-ching-a9b4f',
    storageBucket: 'ka-ching-a9b4f.firebasestorage.app',
    iosBundleId: 'com.example.kaching',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOF9EWnUhY47NcptbWPhFSSrzl5S3pf_o',
    appId: '1:175995407076:ios:2af181831945c986cf7af1',
    messagingSenderId: '175995407076',
    projectId: 'ka-ching-a9b4f',
    storageBucket: 'ka-ching-a9b4f.firebasestorage.app',
    iosBundleId: 'com.example.kaching',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMFWDeIa-IdxzRsT1AfNXF3fGLCoCoGHA',
    appId: '1:175995407076:web:295ffb902beb7e98cf7af1',
    messagingSenderId: '175995407076',
    projectId: 'ka-ching-a9b4f',
    authDomain: 'ka-ching-a9b4f.firebaseapp.com',
    storageBucket: 'ka-ching-a9b4f.firebasestorage.app',
    measurementId: 'G-JQMYCGQFZC',
  );
}
